name: Release Drafter with Date

on:
  push:
    branches:
      - main
      - master

  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Run release-drafter
        id: drafter
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Append release date to draft
        run: |
          echo "## 📦 Release Draft" > body.md
          echo "🗓 Created on: ${{ steps.date.outputs.date }}" >> body.md
          echo "" >> body.md
          echo "${{ steps.drafter.outputs.body }}" >> body.md

      - name: Update release draft with date
        uses: softprops/action-gh-release@v1
        with:
          tag_name: draft-with-date
          body_path: body.md
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
